version: '3'
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    expose:
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443" #port exposed to localhost
    restart: on-failure #restart in case of crash.
  
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on: #WordPress has to configure mariadb database
      - mariadb
    restart: on-failure
    expose: 
      - "9000"

volumes:
  wordpress:
    driver: local #store volume locally
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/llepiney/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind' #Bind Mounts are volumes that mount on the path to host, can be modified by processes outside of docker
      device: '/home/llepiney/data/mariadb'

networks:
  inception:
    driver: bridge
